{
  lib,
  pkgs,
  crane,
  rustToolchainFor,
  cargoPackage ? null,
  profile ? "release",
  bin ? null,
  pname ? null,
  cargoBuildExtraArgs ? "",
  rustFlags ? null,
  doCheck ? true,
  dontStrip ? false,
}:
let
  target = "thumbv6m-none-eabi";
  craneLib = crane.overrideToolchain rustToolchainFor;
  rustToolchain = rustToolchainFor pkgs;

  commonArgs =
    {
      # Keep linker scripts and .cargo/config.toml in the Nix source. The
      # default Cargo-only source filter is too narrow for bare-metal builds.
      src = lib.cleanSource ../.;
      cargoLock = ../Cargo.lock;
      strictDeps = true;
      nativeBuildInputs = [ pkgs.flip-link ];

      CARGO_BUILD_TARGET = target;
      CARGO_PROFILE = profile;

      inherit doCheck dontStrip;
    }
    // lib.optionalAttrs (rustFlags != null) {
      RUSTFLAGS = rustFlags;
    };

  cargoArtifacts = craneLib.buildDepsOnly (
    commonArgs
    // {
      cargoExtraArgs = lib.escapeShellArgs [
        "--locked"
        "--workspace"
        "--lib"
      ];
      inherit cargoBuildExtraArgs;
      # The dummy source generated by crane intentionally omits memory.x and
      # replaces build.rs, so linking the firmware binary here would fail.
      # Building the library is sufficient to cache package dependencies.
      doCheck = false;
    }
  );

  packageCargoExtraArgs = lib.escapeShellArgs (
    [ "--locked" ]
    ++ lib.optionals (cargoPackage != null) [
      "-p"
      cargoPackage
    ]
    ++ lib.optionals (bin != null) [
      "--bin"
      bin
    ]
  );

  crateInfo = craneLib.crateNameFromCargoToml {
    inherit (commonArgs) src;
  };

  resolvedPname =
    if pname != null then
      pname
    else if cargoPackage != null then
      cargoPackage
    else
      crateInfo.pname;

  resolvedMainProgram =
    if bin != null then
      bin
    else if cargoPackage != null then
      cargoPackage
    else
      crateInfo.pname;

  packageArgs =
    commonArgs
    // {
      inherit cargoArtifacts cargoBuildExtraArgs;
      pname = resolvedPname;
      cargoExtraArgs = packageCargoExtraArgs;
      # `.cargo/config.toml` selects the MCU target. Unit tests which do not
      # depend on MCU hardware should instead execute on the build host.
      cargoTestExtraArgs = "--lib --target host-tuple";
    };
in
craneLib.buildPackage (
  packageArgs
  // {
    passthru = {
      inherit
        cargoArtifacts
        commonArgs
        craneLib
        rustToolchain
        target
        ;
      mainProgram = resolvedMainProgram;
    };

    meta.mainProgram = resolvedMainProgram;
  }
)
